// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
insert into users (id, email, display_name)
values ($1::uuid, $2::text, $3::text)
returning id, email, display_name, primary_currency, timezone, created_at, updated_at
`

type CreateUserParams struct {
	ID          uuid.UUID `db:"id" json:"id"`
	Email       string    `db:"email" json:"email"`
	DisplayName *string   `db:"display_name" json:"display_name"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.ID, arg.Email, arg.DisplayName)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.PrimaryCurrency,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :execrows
delete from
  users
where
  id = $1::uuid
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUser, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteUserWithCascade = `-- name: DeleteUserWithCascade :execrows
with removed_from_accounts as (
  delete from
    account_users
  where
    user_id = $1::uuid
  returning
    user_id
)
delete from
  users
where
  id = $1::uuid
`

func (q *Queries) DeleteUserWithCascade(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUserWithCascade, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getUser = `-- name: GetUser :one
select id, email, display_name, primary_currency, timezone, created_at, updated_at from users
where id = $1::uuid
`

func (q *Queries) GetUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.PrimaryCurrency,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
select id, email, display_name, primary_currency, timezone, created_at, updated_at from users
where lower(email) = lower($1::text)
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.PrimaryCurrency,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserPrimaryCurrency = `-- name: GetUserPrimaryCurrency :one
select
  primary_currency
from
  users
where
  id = $1::uuid
`

func (q *Queries) GetUserPrimaryCurrency(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getUserPrimaryCurrency, id)
	var primary_currency string
	err := row.Scan(&primary_currency)
	return primary_currency, err
}

const getUserTimezone = `-- name: GetUserTimezone :one
select
  timezone
from
  users
where
  id = $1::uuid
`

func (q *Queries) GetUserTimezone(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getUserTimezone, id)
	var timezone string
	err := row.Scan(&timezone)
	return timezone, err
}

const listUsers = `-- name: ListUsers :many
select id, email, display_name, primary_currency, timezone, created_at, updated_at from users
order by created_at desc
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.DisplayName,
			&i.PrimaryCurrency,
			&i.Timezone,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :exec
update users
set
  email = $1::text,
  display_name = $2::text,
  primary_currency = coalesce($3::varchar(3), primary_currency),
  timezone = coalesce($4::varchar(50), timezone)
where id = $5::uuid
`

type UpdateUserParams struct {
	Email           *string   `db:"email" json:"email"`
	DisplayName     *string   `db:"display_name" json:"display_name"`
	PrimaryCurrency *string   `db:"primary_currency" json:"primary_currency"`
	Timezone        *string   `db:"timezone" json:"timezone"`
	ID              uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.Exec(ctx, updateUser,
		arg.Email,
		arg.DisplayName,
		arg.PrimaryCurrency,
		arg.Timezone,
		arg.ID,
	)
	return err
}
