-- +goose Up
CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- Update timestamp trigger
-- +goose StatementBegin
CREATE OR REPLACE FUNCTION touch_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at := NOW();
  RETURN NEW;
END$$;
-- +goose StatementEnd

--- users --------------------------------------------------------------
CREATE TABLE users (
  id                 UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  email              TEXT        NOT NULL,
  display_name       TEXT,
  default_account_id BIGINT,
  primary_currency   CHAR(3)     NOT NULL DEFAULT 'CAD',
  timezone           VARCHAR(50) NOT NULL DEFAULT 'America/Toronto',
  created_at         TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at         TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX ux_users_email_ci ON users (lower(email));
CREATE INDEX idx_users_default_account ON users(default_account_id);

CREATE TRIGGER trg_users_update
  BEFORE UPDATE ON users
  FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

--- accounts -----------------------------------------------------------
CREATE TABLE accounts (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_id         UUID        NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  name             TEXT        NOT NULL,
  bank             TEXT        NOT NULL,
  account_type     SMALLINT    NOT NULL DEFAULT 0
                       CHECK (account_type BETWEEN 0 AND 5),
  alias            TEXT,

  anchor_date      DATE        NOT NULL DEFAULT CURRENT_DATE,
  anchor_balance_cents BIGINT  NOT NULL DEFAULT 0,
  anchor_currency  CHAR(3)     NOT NULL DEFAULT 'CAD',

  main_currency    CHAR(3)     NOT NULL DEFAULT 'CAD',
  colors           TEXT[]      DEFAULT ARRAY['#1f2937', '#3b82f6', '#10b981']
                       CHECK (
                         array_length(colors, 1) = 3 AND
                         colors[1] ~ '^#[0-9a-fA-F]{6}$' AND
                         colors[2] ~ '^#[0-9a-fA-F]{6}$' AND
                         colors[3] ~ '^#[0-9a-fA-F]{6}$'
                       ),

  created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CONSTRAINT accounts_owner_name_unique UNIQUE (owner_id, name)
);

CREATE TRIGGER trg_accounts_update
  BEFORE UPDATE ON accounts
  FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

CREATE INDEX idx_accounts_owner ON accounts(owner_id);

-- Add FK for users.default_account_id
ALTER TABLE users
  ADD CONSTRAINT fk_users_default_account
  FOREIGN KEY (default_account_id)
  REFERENCES accounts(id)
  ON DELETE SET NULL;

--- account_users ------------------------------------------------------
CREATE TABLE account_users (
  account_id BIGINT NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
  user_id    UUID   NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  added_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (account_id, user_id)
);

CREATE INDEX idx_account_users_user_account ON account_users(user_id, account_id);

--- categories ---------------------------------------------------------
CREATE TABLE categories (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id    UUID        NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  slug       TEXT        NOT NULL,
  color      TEXT        NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT categories_user_slug_unique UNIQUE (user_id, slug),
  CONSTRAINT slug_lower CHECK (slug = lower(slug))
);

CREATE INDEX idx_categories_user_id ON categories(user_id);

CREATE TRIGGER trg_categories_update
  BEFORE UPDATE ON categories
  FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

--- transaction_rules --------------------------------------------------
CREATE TABLE transaction_rules (
  rule_id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id         UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  rule_name       VARCHAR(255) NOT NULL,

  -- Actions (at least one required)
  category_id     BIGINT REFERENCES categories(id) ON DELETE CASCADE,
  merchant        TEXT,

  conditions      JSONB NOT NULL,
  logic_operator  TEXT NOT NULL DEFAULT 'AND' CHECK (logic_operator IN ('AND', 'OR')),

  is_active       BOOLEAN DEFAULT true,
  priority_order  INTEGER NOT NULL DEFAULT 0,
  rule_source     VARCHAR(20) NOT NULL DEFAULT 'user_created',

  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  last_applied_at TIMESTAMPTZ,
  times_applied   INTEGER DEFAULT 0,

  UNIQUE(user_id, rule_name),
  CONSTRAINT check_has_action CHECK (
    category_id IS NOT NULL OR merchant IS NOT NULL
  )
);

CREATE INDEX idx_rules_user_active_priority
  ON transaction_rules(user_id, is_active, priority_order);

CREATE TRIGGER trg_transaction_rules_update
  BEFORE UPDATE ON transaction_rules
  FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

--- transactions -------------------------------------------------------
CREATE TABLE transactions (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_id       BIGINT       NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,

  email_id         TEXT,
  tx_date          TIMESTAMPTZ  NOT NULL,

  -- Money in cents (simple!)
  tx_amount_cents  BIGINT       NOT NULL,
  tx_currency      CHAR(3)      NOT NULL DEFAULT 'CAD',

  tx_direction     SMALLINT     NOT NULL CHECK (tx_direction BETWEEN 0 AND 2),
  tx_desc          TEXT,

  balance_after_cents BIGINT,
  balance_currency    CHAR(3),

  merchant         TEXT,
  category_id      BIGINT       REFERENCES categories(id) ON DELETE SET NULL,

  category_manually_set BOOLEAN NOT NULL DEFAULT false,
  merchant_manually_set BOOLEAN NOT NULL DEFAULT false,

  suggestions      TEXT[],
  user_notes       TEXT,

  -- Foreign currency (optional)
  foreign_amount_cents BIGINT,
  foreign_currency     CHAR(3),
  exchange_rate        DOUBLE PRECISION,

  created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at       TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TRIGGER trg_transactions_update
  BEFORE UPDATE ON transactions
  FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

CREATE UNIQUE INDEX ux_transactions_email_id_notnull
  ON transactions(email_id) WHERE email_id IS NOT NULL;

-- Performance indexes
CREATE INDEX idx_tx_account_date ON transactions(account_id, tx_date DESC);
CREATE INDEX idx_tx_category_id  ON transactions(category_id);
CREATE INDEX idx_tx_amount_cents ON transactions(tx_amount_cents);
CREATE INDEX idx_tx_currency ON transactions(tx_currency);
CREATE INDEX idx_tx_desc_trgm ON transactions USING gin (lower(tx_desc) gin_trgm_ops);

-- Partial index for uncategorized
CREATE INDEX idx_tx_uncategorized
  ON transactions(tx_date DESC)
  WHERE category_id IS NULL;

-- +goose Down
DROP TABLE IF EXISTS transactions;
DROP TABLE IF EXISTS transaction_rules;
DROP TABLE IF EXISTS categories;
DROP TABLE IF EXISTS account_users;
ALTER TABLE users DROP CONSTRAINT IF EXISTS fk_users_default_account;
DROP TABLE IF EXISTS accounts;
DROP TABLE IF EXISTS users;

-- +goose StatementBegin
DROP FUNCTION IF EXISTS touch_updated_at();
-- +goose StatementEnd

DROP EXTENSION IF EXISTS "pgcrypto";
DROP EXTENSION IF EXISTS pg_trgm;
