-- +goose Up
CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- +goose StatementBegin

CREATE OR REPLACE FUNCTION touch_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at := NOW();
  RETURN NEW;
END$$;
-- +goose StatementEnd

--- users --------------------------------------------------------------

CREATE TABLE users (
  id                 UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  email              TEXT        NOT NULL,
  display_name       TEXT,
  default_account_id BIGINT,
  created_at         TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at         TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX ux_users_email_ci ON users (lower(email));
CREATE INDEX idx_users_default_account ON users(default_account_id);

CREATE TRIGGER trg_users_update
  BEFORE UPDATE ON users
  FOR EACH ROW EXECUTE FUNCTION touch_updated_at();


--- accounts -----------------------------------------------------------

CREATE TABLE accounts (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_id         UUID        NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  name             TEXT        NOT NULL,
  bank             TEXT        NOT NULL,
  account_type     SMALLINT    NOT NULL DEFAULT 0
                       CHECK (account_type BETWEEN 0 AND 5),
  alias            TEXT,
  anchor_date      DATE        NOT NULL DEFAULT CURRENT_DATE,
  anchor_balance   JSONB       NOT NULL DEFAULT '{"currency_code":"CAD","units":0,"nanos":0}'
                       CHECK (
                         jsonb_typeof(anchor_balance) = 'object' AND
                         anchor_balance ? 'currency_code' AND
                         anchor_balance ? 'units' AND
                         anchor_balance ? 'nanos'
                       ),
  created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT accounts_owner_name_unique UNIQUE (owner_id, name)
);

CREATE TRIGGER trg_accounts_update
  BEFORE UPDATE ON accounts
  FOR EACH ROW EXECUTE FUNCTION touch_updated_at();


CREATE INDEX idx_accounts_owner ON accounts(owner_id);
CREATE INDEX idx_accounts_anchor_balance ON accounts USING GIN (anchor_balance);

-- add the foreign key constraint for users.default_account_id after accounts table exists
ALTER TABLE users
  ADD CONSTRAINT fk_users_default_account
  FOREIGN KEY (default_account_id)
  REFERENCES accounts(id)
  ON DELETE SET NULL;

--- account_users ------------------------------------------------------

CREATE TABLE account_users (
  account_id BIGINT NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
  user_id    UUID   NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  added_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (account_id, user_id)
);

CREATE INDEX idx_account_users_user_account ON account_users(user_id, account_id);

--- categories ---------------------------------------------------------

CREATE TABLE categories (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id    UUID        NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  slug       TEXT        NOT NULL,
  label      TEXT        NOT NULL,
  color      TEXT        NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT categories_user_slug_unique UNIQUE (user_id, slug),
  CONSTRAINT slug_lower CHECK (slug = lower(slug))
);

CREATE INDEX idx_categories_user_id ON categories(user_id);

CREATE TRIGGER trg_categories_update
  BEFORE UPDATE ON categories
  FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

--- transactions -------------------------------------------------------

CREATE TABLE transactions (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_id       BIGINT       NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,

  email_id         TEXT,
  tx_date          TIMESTAMPTZ  NOT NULL,
  tx_amount        JSONB        NOT NULL
                       CHECK (
                         jsonb_typeof(tx_amount) = 'object' AND
                         tx_amount ? 'currency_code' AND
                         tx_amount ? 'units' AND
                         tx_amount ? 'nanos'
                       ),
  tx_direction     SMALLINT     NOT NULL
                   CHECK (tx_direction BETWEEN 0 AND 2),
  tx_desc          TEXT,

  balance_after    JSONB,

  merchant         TEXT,
  category_id      BIGINT       REFERENCES categories(id),
  cat_status       SMALLINT     NOT NULL DEFAULT 2
                   CHECK (cat_status BETWEEN 0 AND 4),
  suggestions      TEXT[],

  user_notes       TEXT,

  foreign_amount   JSONB,
  exchange_rate    NUMERIC(18,6),

  receipt_id       BIGINT UNIQUE,

  created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at       TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TRIGGER trg_transactions_update
  BEFORE UPDATE ON transactions
  FOR EACH ROW EXECUTE FUNCTION touch_updated_at();


CREATE UNIQUE INDEX ux_transactions_email_id_notnull
  ON transactions(email_id) WHERE email_id IS NOT NULL;
CREATE INDEX idx_tx_account_date ON transactions(account_id, tx_date);
CREATE INDEX idx_tx_category_id  ON transactions(category_id);
CREATE INDEX idx_tx_desc_trgm    ON transactions USING gin (lower(tx_desc) gin_trgm_ops);
CREATE INDEX idx_tx_amount ON transactions USING GIN (tx_amount);
CREATE INDEX idx_tx_balance_after ON transactions USING GIN (balance_after);
CREATE INDEX idx_tx_foreign_amount ON transactions USING GIN (foreign_amount);

--- receipts -----------------------------------------------------------

CREATE TABLE receipts (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  engine           SMALLINT    NOT NULL
                   CHECK (engine BETWEEN 0 AND 2),
  parse_status     SMALLINT    NOT NULL DEFAULT 1
                   CHECK (parse_status BETWEEN 0 AND 3),
  link_status      SMALLINT    NOT NULL DEFAULT 1
                   CHECK (link_status BETWEEN 0 AND 3),

  match_ids        BIGINT[],

  merchant         TEXT,
  purchase_date    DATE,
  total_amount     JSONB,
  tax_amount       JSONB,

  raw_payload      JSONB,
  canonical_data   JSONB,

  image_url        TEXT,
  image_sha256     BYTEA,

  lat              DOUBLE PRECISION,
  lon              DOUBLE PRECISION,
  location_source  TEXT,
  location_label   TEXT,

  created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at       TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TRIGGER trg_receipts_update
  BEFORE UPDATE ON receipts
  FOR EACH ROW EXECUTE FUNCTION touch_updated_at();


CREATE INDEX idx_receipts_purchase_date ON receipts(purchase_date);
CREATE INDEX idx_receipts_merchant_trgm ON receipts USING gin (lower(merchant) gin_trgm_ops);
CREATE INDEX idx_receipts_total_amount ON receipts USING GIN (total_amount);
CREATE INDEX idx_receipts_tax_amount ON receipts USING GIN (tax_amount);

ALTER TABLE transactions
  ADD CONSTRAINT fk_tx_receipt
  FOREIGN KEY (receipt_id)
  REFERENCES receipts(id)
  ON DELETE SET NULL;

--- receipt_items ------------------------------------------------------

CREATE TABLE receipt_items (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  receipt_id    BIGINT       NOT NULL REFERENCES receipts(id) ON DELETE CASCADE,
  line_no       INT,
  name          TEXT         NOT NULL,
  qty           NUMERIC(18,4) DEFAULT 1,
  unit_price    JSONB,
  line_total    JSONB,
  sku           TEXT,
  category_hint TEXT,
  created_at    TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
  updated_at    TIMESTAMPTZ   NOT NULL DEFAULT NOW()
);

CREATE TRIGGER trg_receipt_items_update
  BEFORE UPDATE ON receipt_items
  FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

CREATE INDEX idx_receipt_items_receipt_id ON receipt_items(receipt_id);
CREATE INDEX idx_receipt_items_name_trgm  ON receipt_items USING gin (lower(name) gin_trgm_ops);
CREATE INDEX idx_receipt_items_unit_price ON receipt_items USING GIN (unit_price);
CREATE INDEX idx_receipt_items_line_total ON receipt_items USING GIN (line_total);

-- +goose Down
DROP TABLE IF EXISTS receipt_items;
ALTER TABLE transactions DROP CONSTRAINT IF EXISTS fk_tx_receipt;
DROP TABLE IF EXISTS receipts;
DROP INDEX IF EXISTS idx_tx_desc_trgm;
DROP INDEX IF EXISTS idx_tx_category_id;
DROP INDEX IF EXISTS idx_tx_account_date;
DROP INDEX IF EXISTS ux_transactions_email_id_notnull;
DROP TABLE IF EXISTS transactions;
DROP TABLE IF EXISTS categories;
DROP TABLE IF EXISTS account_users;
ALTER TABLE users DROP CONSTRAINT IF EXISTS fk_users_default_account;
DROP TABLE IF EXISTS accounts;
DROP INDEX IF EXISTS ux_users_email_ci;
DROP TABLE IF EXISTS users;

-- +goose StatementBegin
DROP FUNCTION IF EXISTS touch_updated_at();
-- +goose StatementEnd

DROP EXTENSION IF EXISTS "pgcrypto";
DROP EXTENSION IF EXISTS pg_trgm;
