-- +goose Up

--- receipts ---------------------------------------------------------------
CREATE TABLE receipts (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id          UUID        NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  transaction_id   BIGINT      REFERENCES transactions(id) ON DELETE SET NULL,
  image_path       TEXT        NOT NULL,
  merchant         TEXT,
  receipt_date     DATE,
  currency         CHAR(3),
  subtotal_cents   BIGINT,
  tax_cents        BIGINT,
  total_cents      BIGINT,
  confidence       REAL,
  status           SMALLINT    NOT NULL DEFAULT 1,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at       TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_receipts_user_id ON receipts(user_id);
CREATE INDEX idx_receipts_user_status ON receipts(user_id, status);
CREATE INDEX idx_receipts_transaction_id ON receipts(transaction_id) WHERE transaction_id IS NOT NULL;

CREATE TRIGGER trg_receipts_update
  BEFORE UPDATE ON receipts
  FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

--- receipt_items ----------------------------------------------------------
CREATE TABLE receipt_items (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  receipt_id       BIGINT      NOT NULL REFERENCES receipts(id) ON DELETE CASCADE,
  raw_name         TEXT        NOT NULL,
  name             TEXT,
  quantity         DOUBLE PRECISION NOT NULL DEFAULT 1,
  unit_price_cents BIGINT      NOT NULL DEFAULT 0,
  unit_currency    CHAR(3)     NOT NULL DEFAULT 'CAD',
  sort_order       INT         NOT NULL DEFAULT 0,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at       TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_receipt_items_receipt_id ON receipt_items(receipt_id);

CREATE TRIGGER trg_receipt_items_update
  BEFORE UPDATE ON receipt_items
  FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

-- +goose Down
DROP TABLE IF EXISTS receipt_items;
DROP TABLE IF EXISTS receipts;
