-- +goose Up
-- Drop receipt_id column from transactions table
ALTER TABLE transactions DROP CONSTRAINT IF EXISTS fk_tx_receipt;
ALTER TABLE transactions DROP COLUMN IF EXISTS receipt_id;

-- Drop receipt_items table
DROP TABLE IF EXISTS receipt_items;

-- Drop receipts table
DROP TABLE IF EXISTS receipts;

-- +goose Down
-- Recreate receipts table
CREATE TABLE receipts (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  engine           SMALLINT    NOT NULL
                   CHECK (engine BETWEEN 0 AND 2),
  parse_status     SMALLINT    NOT NULL DEFAULT 1
                   CHECK (parse_status BETWEEN 0 AND 3),
  link_status      SMALLINT    NOT NULL DEFAULT 1
                   CHECK (link_status BETWEEN 0 AND 3),

  match_ids        BIGINT[],

  merchant         TEXT,
  purchase_date    DATE,
  total_amount     JSONB,
  tax_amount       JSONB,

  raw_payload      JSONB,
  canonical_data   JSONB,

  image_url        TEXT,
  image_sha256     BYTEA,

  lat              DOUBLE PRECISION,
  lon              DOUBLE PRECISION,
  location_source  TEXT,
  location_label   TEXT,

  created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at       TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TRIGGER trg_receipts_update
  BEFORE UPDATE ON receipts
  FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

CREATE INDEX idx_receipts_purchase_date ON receipts(purchase_date);
CREATE INDEX idx_receipts_merchant_trgm ON receipts USING gin (lower(merchant) gin_trgm_ops);
CREATE INDEX idx_receipts_total_amount ON receipts USING GIN (total_amount);
CREATE INDEX idx_receipts_tax_amount ON receipts USING GIN (tax_amount);

-- Recreate receipt_items table
CREATE TABLE receipt_items (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  receipt_id    BIGINT       NOT NULL REFERENCES receipts(id) ON DELETE CASCADE,
  line_no       INT,
  name          TEXT         NOT NULL,
  qty           NUMERIC(18,4) DEFAULT 1,
  unit_price    JSONB,
  line_total    JSONB,
  sku           TEXT,
  category_hint TEXT,
  created_at    TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
  updated_at    TIMESTAMPTZ   NOT NULL DEFAULT NOW()
);

CREATE TRIGGER trg_receipt_items_update
  BEFORE UPDATE ON receipt_items
  FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

CREATE INDEX idx_receipt_items_receipt_id ON receipt_items(receipt_id);
CREATE INDEX idx_receipt_items_name_trgm  ON receipt_items USING gin (lower(name) gin_trgm_ops);
CREATE INDEX idx_receipt_items_unit_price ON receipt_items USING GIN (unit_price);
CREATE INDEX idx_receipt_items_line_total ON receipt_items USING GIN (line_total);

-- Add receipt_id column back to transactions
ALTER TABLE transactions ADD COLUMN receipt_id BIGINT UNIQUE;

ALTER TABLE transactions
  ADD CONSTRAINT fk_tx_receipt
  FOREIGN KEY (receipt_id)
  REFERENCES receipts(id)
  ON DELETE SET NULL;
